### PR TITLE
updates to workbook to handle new scratch org creation

### PR DESCRIPTION
**Pull request by Vchalem**

### CODE REVIEW

**Comment by VivekMChawla** [comment]
@Vchalem can you remove the changes to `sample_docs/config.yml`? I don't think they are required for the main docs changes, are they?

**Comment by Vchalem** [comment]
@VivekMChawla  correct, is there a way to remove a file from a PR? Or should I create a new branch/new commit that doesn't contain that file? thanks!

**Comment by VivekMChawla** [comment]
@Vchalem you should be able to just revert the file in the same branch.  Once you've done that you can submit a new pull request.

**Comment by VivekMChawla** [comment]
Closing this PR as the required changes were added by PR #2

**Pull request closed without merging**
